/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.forecast.config;
import cn.zhuatech.forecast.model.*; import cn.zhuatech.forecast.repository.*; import org.springframework.boot.CommandLineRunner; import org.springframework.context.annotation.*; import org.springframework.security.crypto.password.PasswordEncoder; import java.time.LocalDate; import java.util.List;
@Configuration public class DataInitializer {@Bean CommandLineRunner seed(OperatingUnitRepository units,WorkRecordRepository records,ResourceRegisterRepository resources,ReviewRecordRepository reviews,UserRepository users,PasswordEncoder encoder){return args->{if(units.count()>0)return;
 OperatingUnit east=units.save(new OperatingUnit("FCST-EAST","华东零售计划单元","现代渠道",9000)),ec=units.save(new OperatingUnit("FCST-EC","全国电商计划单元","电商渠道",6000)),south=units.save(new OperatingUnit("FCST-SOUTH","华南零售计划单元","传统渠道",3000));
 WorkRecord a=records.save(new WorkRecord("FCST-260801-031","CAT-BEVERAGE-EAST","华东饮品 8 月滚动预测",east,4280,3972,86,LocalDate.now().plusDays(1),WorkRecord.Status.RUNNING,"ENSEMBLE-V5.1")); WorkRecord b=records.save(new WorkRecord("FCST-260801-028","CAT-PERSONAL-CARE","全国个护促销情景预测",ec,2360,2360,18,LocalDate.now(),WorkRecord.Status.COMPLETED,"PROMO-V3.2")); WorkRecord c=records.save(new WorkRecord("FCST-260801-036","CAT-FROZEN-SOUTH","华南冷冻食品天气修正",south,916,704,27,LocalDate.now().plusDays(2),WorkRecord.Status.RELEASED,"WEATHER-V2.4"));
 resources.saveAll(List.of(new ResourceRegister("MODEL-ENS-051","零售需求集成模型",east,ResourceRegister.Status.RUNNING,93),new ResourceRegister("MODEL-PROMO-032","促销弹性预测模型",ec,ResourceRegister.Status.RUNNING,89),new ResourceRegister("MODEL-NPI-018","新品类比预测模型",south,ResourceRegister.Status.ALARM,74)));
 reviews.saveAll(List.of(new ReviewRecord("FVA-260801-032",a,"预测增值",200,8,ReviewRecord.Result.PENDING,"程望"),new ReviewRecord("FVA-260801-011",b,"促销准确率",120,2,ReviewRecord.Result.PASSED,"叶澜"),new ReviewRecord("FVA-260728-018",c,"决策风险",80,4,ReviewRecord.Result.FAILED,"程望")));
 String demo=encoder.encode("Demo@2026"); users.saveAll(List.of(new UserAccount("operator",demo,"叶澜",UserAccount.Role.DOMAIN_USER,"FCST-EAST"),new UserAccount("planner",demo,"程望",UserAccount.Role.DOMAIN_OPERATOR,null),new UserAccount("quality",demo,"许研",UserAccount.Role.QUALITY,null),new UserAccount("admin",encoder.encode("ZhuaTech@2026"),"系统管理员",UserAccount.Role.ADMIN,null)));};}}
