/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.forecast.controller; import cn.zhuatech.forecast.ai.AiProvider; import cn.zhuatech.forecast.common.ApiResponse; import cn.zhuatech.forecast.dto.ForecastDto.*; import cn.zhuatech.forecast.service.ForecastService; import cn.zhuatech.forecast.service.ForecastScenarioService; import jakarta.validation.Valid; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.web.bind.annotation.*; import java.util.Map;
/**
 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
 */
@RestController @RequestMapping("/api/shopfloor") @PreAuthorize("hasAnyRole('DOMAIN_USER','ADMIN')") public class WorkspaceController {private final ForecastService service;private final AiProvider ai;private final ForecastScenarioService scenario;/**
                                                                                                                                                                                                                                                         * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                         */
public WorkspaceController(ForecastService service,AiProvider ai,ForecastScenarioService scenario){this.service=service;this.ai=ai;this.scenario=scenario;}/**
                                                                                                                                                                                                                                                                                                                                                                                                                    * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                    */
@GetMapping("/dashboard") public ApiResponse<Dashboard> dashboard(){return ApiResponse.ok(service.shopfloorDashboard());}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             */
@PostMapping("/work-orders/{id}/reports") public ApiResponse<ReportResult> report(@PathVariable Long id,@Valid @RequestBody ReportRequest request){return ApiResponse.ok("反馈提交成功",service.report(id,request));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            */
@PostMapping("/ai-preview") public ApiResponse<AiProvider.AiResult> preview(@RequestBody Map<String,String> body){return ApiResponse.ok(ai.execute(body.getOrDefault("prompt",""),Map.of("mode","demo")));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       */
@PostMapping("/forecast-scenario") public ApiResponse<ForecastScenarioService.ScenarioResult> simulate(@Valid @RequestBody ForecastScenarioService.ScenarioRequest request){return ApiResponse.ok("预测情景生成完成",scenario.simulate(request));}}
